# Model arguments
model_name_or_path: allenai/OLMo-2-1124-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/OpenR1-Math-220k
dataset_num_proc: 4

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/OLMo-2-1124-7B-Instruct_SFT
hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: true
max_length: 2048
max_steps: 2000
num_train_epochs: 1
output_dir: data/allenai/OLMo-2-1124-7B-Instruct_SFT
overwrite_output_dir: true
# packing: false
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 1
seed: 42
torch_compile: true
use_liger: true
warmup_ratio: 0.05