# Model arguments
# You need to download the model and manually change the rope to 300k and max_position_embeddings to 32768
# the config file should match https://huggingface.co/open-r1/OpenR1-Qwen-7B/blob/main/config.json
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2
trust_remote_code: True

# Data training arguments
dataset_name: open-r1/OpenR1-Math-220k
dataset_num_proc: 48

#SFT hyperparam
max_length: 32768
weight_decay: 0.0001
optim: adamw_torch
lr_scheduler_type: linear
warmup_ratio: 0.1
learning_rate: 5.0e-05
gradient_accumulation_steps: 2
per_device_eval_batch_size: 8
per_device_train_batch_size: 8

# SFT trainer config
max_steps: -1
num_train_epochs: 1
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/Qwen2.5-7B-SFT_GRPO${VERSION}
hub_model_revision: v${VERSION}
hub_strategy: every_save
log_level: info
logging_steps: 1
logging_strategy: steps
packing: false
output_dir: data/Neelectric/Qwen2.5-7B-SFT_GRPO${VERSION}
overwrite_output_dir: true
push_to_hub: true
report_to:
- wandb
save_strategy: "steps"
save_steps: 0.1
save_total_limit: 1
seed: 42
use_liger_kernel: true
wandb_entity: Neelectric
wandb_project: open-r1_SFT
run_name: Qwen/Qwen2.5-7B-Instruct_SFT${VERSION}
callbacks:
- push_to_hub_revision
benchmarks:
- math_500_8k
- aime24_8k
- gsm8k_8k #uncommented for now out of worry this will crash the process at the end