# Model arguments # inspired in part by https://github.com/huggingface/open-r1/blob/smollm-grpo-configs/recipes/SmolLM2-1.7B-Instruct/grpo/config_v04.00.yaml
model_name_or_path: allenai/OLMo-2-1124-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
# We edit the DeepSeek chat template to ensure (a) the reasoning block within <think> and </think> is included in the completion and (b) the <think> tag is not part of the prefill so that the format reward works
# chat_template: "{% for message in messages %}{% if loop.first and messages[0]['role'] != 'system' %}{{ '<|endoftext|><|system|>\nYou are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>\n' }}{% endif %}{{'<|user|>' + '\n' + message['content'] '\n'}}{% endfor %}{% if add_generation_prompt %}{{ '<|assistant|>' }}{% endif %}"

system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"

dataset_name: Neelectric/OpenR1-Math-cn_k12-91k
dataset_prompt_column: problem

# GRPO hyperparam
optim: adamw_torch
lr_scheduler_type: constant_with_warmup #also see by https://kalomaze.bearblog.dev/grpo-judge-experiments-findings-and-empirical-observations/
# lr_scheduler_kwargs:
#   min_lr_rate: 0.1
warmup_ratio: 0.1
learning_rate: 5.0e-06 # https://wandb.ai/huggingface/open-r1/runs/2d9grsso?nw=nwuseredbeeching here even more aggressive 1e-4
gradient_accumulation_steps: 1
per_device_eval_batch_size: 1
per_device_train_batch_size: 16
num_generations: 28
max_grad_norm: 0.05  # see also https://kalomaze.bearblog.dev/grpo-judge-experiments-findings-and-empirical-observations/
padding_free: true # following https://github.com/huggingface/trl/pull/3076
beta: 0.0 # following DeepSeekMath paper # hyperparameter to scale the negative D_{KL} term in GRPO objective. So the higher the beta, the more we penalize moving away from our reference policy.
epsilon: 0.2 # by default, 0.2. This dictates the clipping like in PPO, so where r = ratio(current policy/old policy), we use e for clip(r, 1 - e, 1 + e) * Advantage. So for 0.2 we clip the ratio to be within [0.98, 1.02]. Smaller e = tighter clip!
scale_rewards: false #true according to https://wandb.ai/huggingface/open-r1/runs/3j51s8ub/overview #false according to https://github.com/huggingface/trl/releases/tag/v0.16.0
num_iterations: 1 # according to this! https://github.com/huggingface/trl/releases/tag/v0.16.0
disable_dropout: true #following this https://github.com/huggingface/trl/releases/tag/v0.17.0#:~:text=3276,to%20disable%20dropout
loss_type: "dr_grpo"
shuffle_dataset: true
mask_truncated_completions: true
use_liger_loss: false #unfortunately only compatible with bnpo

# GRPO trainer config
bf16: true
max_steps: 817 # we have num_iterations at 4, so the otherwise 817 steps would be consumed 4 times too quickly!
num_train_epochs: 1
use_vllm: true
vllm_device: "cuda:7"
vllm_gpu_memory_utilization: 0.7
do_eval: false
eval_strategy: 'no'
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/OLMo-2-1124-7B-Instruct_GRPO${VERSION}
hub_model_revision: ${VERSION}
hub_strategy: every_save
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
packing: false
max_completion_length: 2048
max_prompt_length: 512
output_dir: data/Neelectric/OLMo-2-1124-7B-Instruct_SFT${VERSION}
overwrite_output_dir: true
push_to_hub: true
report_to:
- wandb
reward_funcs:
- accuracy
- format # maybe enforce "formatting reward as a flat 0.2 bonus that only applies when the judgement is also correct." as per https://kalomaze.bearblog.dev/grpo-judge-experiments-findings-and-empirical-observations/
# - tag_count
reward_weights:
- 1.0
- 0.2
# - 0.1
save_strategy: "steps"
save_steps: 0.05
save_total_limit: 2
seed: 42
torch_compile: false
use_liger_kernel: true
temperature: 0.6 #taken from https://wandb.ai/huggingface/open-r1/runs/2d9grsso?nw=nwuseredbeeching
wandb_entity: Neelectric
wandb_project: open-r1_GRPO
run_name: allenai/OLMo-2-1124-7B-Instruct_GRPO${VERSION}

#  eval callbacks
callbacks:
- push_to_hub_revision
# benchmarks:
# - math_500_8k
# - aime24_8k
# - gsm8k_8k #uncommented for now out of worry this will crash the process at the end