# Model arguments
model_name_or_path: allenai/OLMo-2-1124-7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
system_prompt: "You are a helpful AI Assistant that provides well-reasoned and detailed responses. You first think about the reasoning process as an internal monologue and then provide the user with the answer. Respond in the following format: <think>\n...\n</think>\n<answer>\n...\n</answer>"
dataset_name: Neelectric/OpenR1-Math-220k_CN-K12_OLMo-2_4096toks
dataset_num_proc: 48

# Shared hyperparams
bf16: true
callbacks:
- push_to_hub_revision
# benchmarks:
# # - math_500_8k
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/OLMo-2-1124-7B-Instruct_GRPO${VERSION}
hub_model_revision: ${VERSION}
hub_strategy: every_save
learning_rate: 2.0e-06 
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: constant_with_warmup 
max_grad_norm: 0.05
max_steps: -1 # check with num_iterations!
num_train_epochs: 1
optim: adamw_torch
# output_dir: data/Neelectric/OLMo-2-1124-7B-Instruct_GRPO${VERSION}
# overwrite_output_dir: true
packing: false
padding_free: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 8
push_to_hub: true
report_to:
- wandb
run_name: allenai/OLMo-2-1124-7B-Instruct_GRPO${VERSION}
save_strategy: "steps"
save_steps: 0.05
save_total_limit: 1
seed: 42
torch_compile: false
use_liger_kernel: true
wandb_entity: Neelectric
wandb_project: open-r1_GRPO
warmup_ratio: 0.1



# GRPO hyperparams
beta: 0.0 
dataset_prompt_column: problem
disable_dropout: true #following this https://github.com/huggingface/trl/releases/tag/v0.17.0#:~:text=3276,to%20disable%20dropout
epsilon: 0.1
log_completions: true
loss_type: "dr_grpo"
mask_truncated_completions: true
max_completion_length: 4096 # without this we might have a pretty major bias vs SFT?
max_prompt_length: 2048
num_iterations: 1 # according to this! https://github.com/huggingface/trl/releases/tag/v0.16.0
num_generations: 6
reward_funcs:
- accuracy
- format
reward_weights:
- 1.0
- 0.1
scale_rewards: false #true according to https://wandb.ai/huggingface/open-r1/runs/3j51s8ub/overview #false according to https://github.com/huggingface/trl/releases/tag/v0.16.0
shuffle_dataset: true
temperature: 0.6 #taken from https://wandb.ai/huggingface/open-r1/runs/2d9grsso?nw=nwuseredbeeching
# use_liger_loss: false #unfortunately only compatible with bnpo
use_vllm: true
vllm_device: "cuda:6"
vllm_gpu_memory_utilization: 0.8