# Model arguments
model_name_or_path: HuggingFaceTB/SmolLM2-1.7B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: open-r1/OpenR1-Math-220k
dataset_num_proc: 16

# SFT trainer config
bf16: true
do_eval: false
eval_strategy: 'no'
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Neelectric/SmolLM2-1.7B-Instruct_SFT${VERSION}
hub_strategy: every_save
learning_rate: 5.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
packing: false
max_grad_norm: 1.0
max_length: 8192
max_steps: 2000
num_train_epochs: 1
output_dir: data/Neelectric/SmolLM2-1.7B-Instruct_SFT${VERSION}
overwrite_output_dir: true
padding_free: true
per_device_train_batch_size: 16
push_to_hub: true
report_to:
- wandb
save_strategy: "epoch"
save_total_limit: 1
seed: 42
torch_compile: true
use_liger: true
warmup_ratio: 0.1
wandb_entity: Neelectric
wandb_project: open-r1
run_name: nvidia/AceInstruct-1.5B_GRPO${VERSION}

#  eval callbacks
callbacks:
- push_to_hub_revision
benchmarks:
- math_500_8k
- aime24_8k
- gsm8k_8k #uncommented for now out of worry this will crash the process at the end
